blueprint:
  name: Zigbee2MQTT - Knob (Operation Mode = event)
  description: Automate your Knob
  domain: automation
  input:
    switch:
      name: Smart Knob
      description: Smart Knob used as Button
      selector:
        entity:
          integration: mqtt
          domain: sensor
          multiple: false
    button_short_press:
      name: Single Press
      description: Action to run on single press (careful not to turn knob instead)
      default: []
      selector:
        action: {}
    button_rotate_right:
      name: Rotate Right
      description: Action to run when Smart Knob is rotated right
      default: []
      selector:
        action: {}
    button_rotate_left:
      name: Rotate Left
      description: Action to run when Smart Knob is rotated left
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/zigbee2mqtt-tuya-moes-smart-knob-ers-10tzbvk-aa/419989
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input 'switch'
  attribute: action
action:
- variables:
    command: '{{ trigger.to_state.state }}'
- choose:
  - conditions:
    - '{{ command == ''single'' }}'
    sequence: !input 'button_short_press'
  - conditions:
    - '{{ command == ''rotate_right'' }}'
    sequence: !input 'button_rotate_right'
  - conditions:
    - '{{ command == ''rotate_left'' }}'
    sequence: !input 'button_rotate_left'
